### ISSUE TITLE
[Feature Request]: Exporting .so files in packages

### ISSUE THREAD

**Issue by min-nguyen** [stefan-hoeck/idris2-pack#115]
Currently when using an Idris package that calls a FFI function on a C `.so` file, that `.so` needs to be in the current directory of or on the `LD_LIBRARY_PATH/PATH` of the user. 

It would be great if dependencies on such files could be exported along with with the Idris package.

---

As a test case, the [distributions](https://github.com/idris-bayes/distributions) package has an Idris function `Statistics.Distribution.GSL.init_rng` that calls a custom C function `init_gsl_rng()` from `distributions.so`.

One can test whether other projects can successfully use `init_rng` by:

1. Adding the following to `~/.pack/user/pack.toml`
```
[custom.all.distributions]
type   = "github"
url    = "https://github.com/idris-bayes/distributions"
commit = "latest:master"
ipkg   = "distributions.ipkg"
```

2. Adding `distributions` to the `depends` of an `ipkg` file.

3. Executing the following code snippet:
```idris
import Statistics.Distribution.GSL
import Statistics.Distribution.Binomial

testSeed : IO () 
testSeed = print $ let seed = GSL.init_rng
                   in  (binomial_gsl 17 0.5 seed)
```

**Comment by stefan-hoeck** [comment]
This should have been fixed. If not, feel free to reopen the issue.
