### ISSUE TITLE
LSP integration

### ISSUE THREAD

**Issue by Z-snails** [stefan-hoeck/idris2-pack#13]
LSP must be built with the same version of idris2 as is being used in the project.
This can be done manually, but it would be nice if `pack` could do this.

I can work on this, just wondering if you had any ideas for this already.

Also does pack have a global config? (to tell if I need to build lsp when installing a new toolchain/pack-db version)

**Comment by Z-snails** [comment]
Actually I have a better idea: A (user customisable) set of packages which are auto-installed when you install a new version of pack-db

**Comment by stefan-hoeck** [comment]
I'll be thinking about these things. About LSP being built with its own version of Idris2: I'm not sure this is in the spirit of a curated package set. The idea is rather, that all packages can be built with the same Idris2 compiler. This would make it much easier, for instance, to have Idris2 LSP depend on other projects.

Actually, this touches on a more general issue: What do we do with failing packages? If we have - for instance - nightly generated package collections, how do we proceed with those packages that fail to build? Ideally, we'd have an automated way to inform upstream for them to fix their packages. Until that's done, a failing package and all packages that (transitively) depend on it should not be included in the package collection.

But all of this is just me thinking out loud, and I'd definitely be interested in your thoughts on this.

**Comment by Z-snails** [comment]
I was unclear, what I meant by lsp needing to be built by the same version of idris, is the same version of idris that is being used to compile other projects lsp is being used to edit. It, like other projects, might break (perhaps more often than most) with new idris versions, so some nightlys might be missing it.

In this case, for pack users it could be helpful to be able to filter nightlys by what projects they have/don't have.

For library authors (speaking from what I would be happy with) I agree a way to notify when it fails would be useful. I can't immediately think of a good way to do this.
I don't think failing packages should be included in nightlys as that would be a bad experience for users

There are some other features/ideas I have, can I share them here or elsewhere (ie discord for a less formal discussion)?

**Comment by stefan-hoeck** [comment]
> I was unclear, what I meant by lsp needing to be built by the same version of idris, is the same version of idris that is being used to compile other projects lsp is being used to edit. It, like other projects, might break (perhaps more often than most) with new idris versions, so some nightlys might be missing it.

I fully agree with this. I also had a quick look at how this is done with Haskell's *stack*. The have some automation going on on GitHub, but a lot of the selecting (and dropping, in case of unresponsive maintainers) of packages is still manual work. Even then, it will usually take several days before all package maintainers have updated their packages to the latest Idris changes.

> In this case, for pack users it could be helpful to be able to filter nightlys by what projects they have/don't have.

That's a good idea and not too hard to implement (I guess). At the moment, all package sets (I probably *should* call them *nightlys*, although this might lead to expectations about there being a new nightly ever - well - night) are downloaded from this repo with `pack update-db`. Filtering them by a list of must-have package names shouldn't be too hard.
 
> For library authors (speaking from what I would be happy with) I agree a way to notify when it fails would be useful. I can't immediately think of a good way to do this. I don't think failing packages should be included in nightlys as that would be a bad experience for users

I definitely agree. The community is still small, so notifying people on Discord or via GitHub issues should be fine for the moment. (Partial) automation can come later.

> There are some other features/ideas I have, can I share them here or elsewhere (ie discord for a less formal discussion)?

Discord should be fine for such a discussion. You can PM me or discuss this openly (probably in a new thread in the package-manager channel).

**Comment by stefan-hoeck** [comment]
I added support for patching `.ipkg` files in #17 . In addition, `lsp` was updated so it contains now a `prebuild` hook in its `.ipkg` file, which also generates the necessary source files. I'll therefore close this. I'm in the process of writing several feature requests. Among those will also be one about user customization where we can pick up other ideas mentioned here and on discord.
