### ISSUE TITLE
Feature Request: Add a flag to use globally installed packages for the REPL

### ISSUE THREAD

**Issue by MonAaraj** [stefan-hoeck/idris2-pack#133]
Hello! I have been using this project for a while and I really love how it works, great job! But to go on with my request:
I think it would be very helpful to add a flag that allow the usage of globally installed packages through the REPL, something like 
``pack repl --global-pkgs repl``, which I'd suggest to be off by default, to avoid any interference with local ``.ipkgs``.

My usage of "global packages" might sound confusing, so to make it clear; I mean packages installed with `pack install package`, without being used in something like a project's ipkg file or such, if there's even a line between those two (which I generally found to be in haskell tooling, but I get a feeling that taking things from there without thinking it over might inherit some issues from them).

**Comment by stefan-hoeck** [comment]
Pack does not keep track about how a package was installed (manually vs. automatically via a dependency), so at the moment it would only be possible to load all installed packages of the current package collection. Perhaps we could use a `pack.toml` setting for this (a list of packages to be automatically loaded into a REPL session if no `.ipkg` file is in scope or option `--global-pkgs` is set explicitly)?

**Comment by MonAaraj** [comment]
I agree about using a pack.toml setting. Though at the risk of stating the obvious, I think the dependencies in that package should also be brought in, and possibly just `contrib` by default if it doesn't harm?

**Comment by stefan-hoeck** [comment]
I'm not sure about the contrib default. Contrib is supposed to be split up eventually, so it shouldn't get any special treatment in my opinion.

**Comment by MonAaraj** [comment]
Ah, I didn't know about that. Then yeah, I completrly agree!

**Comment by stefan-hoeck** [comment]
Would you mind giving this a try yourself? I could surely give you some guidance / places to start with this, but overall I don't think this will be too difficult to implement. Otherwise I'll give this a go eventually, but there are a couple of other feature I'd like to look at first.

**Comment by stefan-hoeck** [comment]
I finally got around to add this as a new feature. See #169 . This adds a new `idris2.repl.autoload` field to the `pack.toml` files, where users can specify the packages to load automatically into a REPL session in the absence of an `.ipkg` file in scope. Possible values are:

- "none" : No packages will be automatically loaded (the default)
- "installed" : All installed packages will be automatically loaded
- "autolibs"  : The list of packages listed under `install.libs` will be loaded
- <list of package names> : The given list of packages will be loaded

In all cases the packages will be loaded together with their (transitive) dependencies, all of which will first be built and installed if missing. In addition, there is the `-p` or `--packages` command line option to give a list of packages to be loaded explicitly.

**Comment by stefan-hoeck** [comment]
This has been merged. If you find the time, could you give it a try and - if all goes well - close this issue afterwards? You can use `pack update` to download and install the latest commit.

**Comment by MonAaraj** [comment]
Thank you very much! It looks perfect, I'll close this issue.
