### ISSUE TITLE
Feature request: warn if a `depends` directory or setting overrides `pack`'s dependecies unintentionally

### ISSUE THREAD

**Issue by ohad** [stefan-hoeck/idris2-pack#135]
`pack` gets a bit confused if there's a local `depends` directory.
Would it make sense to issue a warning if there's a `depends` directory that overrides/changes the dependencies in `pack`?

I think this ought to be a warning, not an error, and we ought to have the ability to suppress it by a flat and a local pack.toml option, because some projects might want to have more complex dependency structures than we expect, and ignoring warnings is a slipper slope :).

**Comment by stefan-hoeck** [comment]
Yes, we should definitely have this. I guess a `--no-warn-depends` command line option (plus similar option in `pack.toml`) would be ok to turn this off?

Do you know if Idris even considers the packages installed in `PACKAGE_PATH` if there is a local `depends` folder?
