### ISSUE TITLE
`pack switch/install` fails if an executable is invoked while pack is still installing

### ISSUE THREAD

**Issue by Z-snails** [stefan-hoeck/idris2-pack#152]
Steps to reproduce

```
pack switch nightly-...
```
(where nightly-... is a new/not yet installed package set)
While that is running
```
idris2
```

The `pack switch ...` then fails

This problem is also triggered when installing idris2-lsp and starting that.

(This is mainly caused when I am to impatient to wait for `pack switch` to finish before starting to code)

**Comment by stefan-hoeck** [comment]
I'm afraid I can't reproduce this. Are you on the latest pack version (otherwise, run `pack update`)? I think this could be related to #139, where a similar issue has been fixed.

**Comment by Z-snails** [comment]
I have not updated pack, but that should fix it.
