### ISSUE TITLE
support `pack run`, `pack exec`, `pack install-app`  for node backend.

### ISSUE THREAD

**Issue by running-grass** [stefan-hoeck/idris2-pack#156]
when i run pack --cg node exec src/Main.idr ,I get  error. sh: build/exec/_tmppack: Permission denied 
I think there are two reasons
1. The generated file does not have executable permissions
2. There is no #!/usr/bin/env node  in the first line of the generated file

**Comment by stefan-hoeck** [comment]
Implemented in #157 .
