### ISSUE TITLE
[ ux ] Slightly misleading error message is printed when command is not completed

### ISSUE THREAD

**Issue by buzden** [stefan-hoeck/idris2-pack#165]
Imagine I don't remember syntax for all `pack` commands yet ;-) I'm still learning. But imagine that I remember there was a `build` command. I remember similar command from, say, `stack` or `sbt` and I try to run simply `pack build` and I get `Unknown command: build`. Hmm... I must have forgotten the name of a command, what was it? Well, then I realise that I forgot not the command name, but its syntax, i.e. the fact that it actually takes an argument!

From the user experience view, error messages could have been slightly more helpful, e.g. saying that this command requires additional parameters.

**Comment by stefan-hoeck** [comment]
I'm having a go at this at the moment. This will be quite a large change, but I plan to also allow `pack help <cmd>` to get detailed help for every specific command, and only print a list of available commands for `pack help`. Hopefully, I have a PR ready in a couple of days.
