### ISSUE TITLE
Update PATH during install

### ISSUE THREAD

**Issue by joelberkeley** [stefan-hoeck/idris2-pack#170]
I'd like pack to add itself to PATH on install. I assume there's a reason this isn't already the case. What might that be?

**Comment by stefan-hoeck** [comment]
I'm not sure how pack should do that. Edit the `$PATH` variable in a config file? Or add a symlink to a `bin` folder?

**Comment by joelberkeley** [comment]
I won't claim to authoritatively know how one should do this, but ...

I personally do the former - specifically `.bashrc` since I use bash.

I'm not sure how adding a symlink would work. Which `bin` folder would we add it to?

**Comment by stefan-hoeck** [comment]
I'd rather not mess with users' config files, nor do I know if other tools do this automatically (if any). Do you? I agree about the `bin` dir: We do not know, which one to use. This is typically the task of (operating system) package managers.

**Comment by joelberkeley** [comment]
rustup does it. On running the installer
```
This path will then be added to your PATH environment variable by
modifying the profile files located at:

  /home/joel/.profile
  /home/joel/.bashrc
```

**Comment by joelberkeley** [comment]
it then asks
```
1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
```
and if you choose "customize" you can then choose not to modify PATH

**Comment by stefan-hoeck** [comment]
I'm still reluctant to add this, but if you want to give it a go, I'll accept a PR as long as it includes a *customize* option as shown in your post above.

**Comment by joelberkeley** [comment]
OK. I don't care about it enough to add it when you're not keen
