### ISSUE TITLE
[ feature request ] Add an ability to specify particular list of packages for which there is no need for safety prompt

### ISSUE THREAD

**Issue by buzden** [stefan-hoeck/idris2-pack#177]
Safety prompt is a great feature, but it gets too pesky when you are (for some reason, say, for development) constantly rebuilding couple of packages with build hooks. Or, say, when you add some package or application to the must-have list, you get several questions for build hooks not at `build` command, but at `switch` one.

I think, listing kind of a white-list of packages which I don't want to receive a safety prompt when still having this "on" by default could be great.

**Comment by stefan-hoeck** [comment]
That's a great idea. I'll see what I can do.

**Comment by stefan-hoeck** [comment]
I opened a PR adding this capability. Could you please have a look if this is what you had in mind @buzden? PR #186.
