### ISSUE TITLE
[ feature request ] An ability for `pack.toml` to say that it is not the top-level one

### ISSUE THREAD

**Issue by buzden** [stefan-hoeck/idris2-pack#185]
I originally was wrongly reading documentation, thinking that `pack` searches for all `pack.toml`s in all parent directories up to the top, not stopping at the first one. And I thought it is very convenient: say, I can define new local packages, say, common definitions for tests or different examples of a library usage independently, not putting everything in a single `pack.toml`. Also, this defines, shall we say, namespaces for package names (however, not sure that `pack` works with this nicely).

When I realised that `pack` searches for the first `pack.toml`, I thought, maybe, it would be a good idea to have a way to say in `pack.toml` that this one is not the toplevel one, so that `pack` would search further? What do you think?

**Comment by stefan-hoeck** [comment]
I'm not sure about this. I want to be careful about not adding too much additional complexity to `pack.toml` files. Could you describe in detail why the feature you describe would be useful: What use case would it make possible?

**Comment by buzden** [comment]
> Could you describe in detail why the feature you describe would be useful: What use case would it make possible?

Maybe, I'm strange with this, but I decided to combine `pack` (including for running tests) and both `golden` and `hedgehog` (since I need both tests for functionality and for compilability for a library + `golden` gives a pretty structured final report and I don't know which another library can give such at the moment, AFAIK, no port of something like `hspec` exists).

BTW, you can [see this structure yourself](https://github.com/buzden/idris2-summary-stat), since this is a real project, despite a WIP one.

So, my project has the following structure: it has an `src` dir at the top with library's code and `tests` dir at the top for tests' code. It has `pack.toml` at the top since I want tests code to use my library in `depends` section of their `*.ipkg` files. So, I've added to the top `pack.toml` two `[custom.all.*]` blocks: one for library, one for the runner of tests. Now I happily can get rid of makefile for running tests, since I can type `pack run my-library-tests` for this.

But, since I'm using `golden` as the top runner for my tests, I have a lot of subpackages with their own `*.ipkg` files inside. I realised that I need some common code for that (BTW, there is another my project which build system haven't migrated to `pack` yet, where I used an [ugly trick of lots of symlinks](https://github.com/buzden/deptycheck/tree/master/tests/gen-derivation/derivation/least-effort/print/adt/001%20trivial) to common code and a lot of symlinks for `depends` dirs).

Okay, it means that I need to create a package for a library of the common code and to add it to some usable `pack.toml` so that tiny `*.ipkg` of individual tests could add it an `depends` lists. For now, it means that this library should be added to the topmost `pack.toml` despite that it is usable only inside `tests` dir.

You know, while describing, I feel this problem minuscule, however, I have in mind a not yet migrated to `pack` a bit bigger project where despite the main library, its tests and several packages of common code (since, some common testing would depend on one part of the library and another common testing code would depend on another), there is more, like a subpackage of an application which uses the library, plus its own tests, and maybe some common testing code. Looks like I will need to have pretty a lot of blocks inside the toplevel `pack.toml` where approximately only half of them relate to what I will want to pass to `pack` as a package name on the top, the rest is somewhat "details of implementation" of my test.

But, finally, anyway, all what I'm writing about is not a use-case that is *impossible* without changes to `pack`, all this is just seeming *strangeness* of a project structure.

**Comment by stefan-hoeck** [comment]
Thanks for your detailed explanation. I think I start seeing where this is headed to. The question for me is: How could we implement this in pack and what would the semantics of such a packaging setup be?

Also: Would it help to be able to have some kind of import list in a `pack.toml` file: Paths to other `pack.toml` files found elsewhere on the system? That probably shouldn't be too hard to set up. However, we'd need to decide on the order in which potentially conflicting settings from different `pack.toml` files would be merged: Which setting should take precedence?

Finally, in case of complex project structures, would a setup with many `pack.toml` files at different locations in the project folders be harder or easier to maintain? That is: Is such a change worth the complexity it adds to pack and `pack.toml` files?

**Comment by buzden** [comment]
> The question for me is: How could we implement this in pack and what would the semantics of such a packaging setup be?

My feeling that implementation of this logic should reside in `Pack.Config.Environment` in `getConfig`, where `findInParentDirs` happens. After `readFromTOML` one should look for "I'm not a toplevel config" key (say, `"meta.toplevel"`) and while this is "false" continue `findInParentDirs` with next dir, until the very top.

On semantics, see below.

> Also: Would it help to be able to have some kind of import list in a `pack.toml` file: Paths to other `pack.toml` files found elsewhere on the system? That probably shouldn't be too hard to set up. However, we'd need to decide on the order in which potentially conflicting settings from different `pack.toml` files would be merged: Which setting should take precedence?

I also thought about this, but I think this is much harder both for user and for `pack` implementation. Arbitrary including is not linear, and potentially cycling. Moreover, you need to know precisely when included `pack.toml` resides.

Logic from my original suggestion (comparing to arbitrary inclusions) is straightforward: all `pack.toml` files are in a (non-cyclic) directories tree, they are fully ordered and those which are lower in the structure (i.e., closer to the point where action is performed) take precedence. And all those `pack.toml` files are divided to kinds of "solid" and "difference", difference `pack.toml`'s are *meant* to modify the contents of the top files, where solid are *meant* to contain enough. Solid files either do not have any `meta.toplevel` key, or have it set to `true`, difference one have this key to `false`.

> Finally, in case of complex project structures, would a setup with many `pack.toml` files at different locations in the project folders be harder or easier to maintain? That is: Is such a change worth the complexity it adds to pack and `pack.toml` files?

Honestly, I don't know whether it is easier to maintain such structure or not, I have no experience with this yet. My subjective feeling that it would be, and that's why I created this feature request, but I'm not 100% sure.

I think that `pack.toml` files' complexity does not suffer at all, since defaults does not change, in my view, i.e. all `pack.toml` files without any additions remain toplevel and logic of all existing files does not change.

I hope that `pack` itself does not raise too much complexity since only in one place a linear piece of code becomes a cycle.

**Comment by stefan-hoeck** [comment]
This is much clearer now, thanks a lot. There is one obstacle, however: At the moment, we are looking for `pack.toml` files from the current working directory (which is the directory from where we invoke `pack`) upward. However, with this change we'd have to start looking from different working directories upward, depending on the command we run. Even worse: If we install or run several local packages in a single run, we'd have to assemble the config for each of them separately, because each of them might have custom `pack.toml` files in their proximity, some of which might even be at odds with each other. So, unless I'm missing something obvious, this is going to be quite a bit harder to get right than you might think.

For instance, assume in my multi-package setup I have packages `A` and `B`, each with their own local `pack.toml` file and package `C` depending both, `A`, and `B`. If we build `C`, we first have to build `A`, and hence, use its local `pack.toml` file. For `B`, we again have to use its local `pack.toml` file (and drop the customizations introduced by `A`'s `pack.toml` file). Finally, `C` might yet again have its own local `pack.toml` file, so we need to reassemble the application environment yet again.

Or am I getting this all completely wrong?

**Comment by buzden** [comment]
> However, with this change we'd have to start looking from different working directories upward, depending on the command we run. Even worse: If we install or run several local packages in a single run, we'd have to assemble the config for each of them separately, because each of them might have custom `pack.toml` files in their proximity, some of which might even be at odds with each other. So, unless I'm missing something obvious, this is going to be quite a bit harder to get right than you might think.

I don't understand why it is true... I thought that if for now we are looking for local `pack.toml` starting from the current directory (including all subbuilds), there should be no change in this logic.

> For instance, assume in my multi-package setup I have packages `A` and `B`, each with their own local `pack.toml` file and package `C` depending both, `A`, and `B`. If we build `C`, we first have to build `A`, and hence, use its local `pack.toml` file. For `B`, we again have to use its local `pack.toml` file (and drop the customizations introduced by `A`'s `pack.toml` file). Finally, `C` might yet again have its own local `pack.toml` file, so we need to reassemble the application environment yet again.

Oh, my logic was completely different. I meant non-toplevel `pack.toml`s only for those packages and apps that cannot be used outside the dir where this `pack.toml` resides. In my example, there was a tiny lib with common definitions for tests and it makes sense only inside the `tests` dir, thus it is defined in `tests/pack.toml`. But as soon as there is a multi-module project with several libs that can be used from outside the context of their dirs, then they should be declared in an upper `pack.toml`. In your example, I would declare all `A`, `B` and `C` in the toplevel `pack.toml`.

I.e. in the logic I mean, `pack.toml` says "everything I declare is relevant to the dir where I am and downwards and is irrelevant in dirs upwards". But at the same time, a top-level `pack.toml` says "everything declared upwards is irrelevant", where non-top-level `pack.toml` says "everything upwards is relevant".

The mechanism I propose is like `.gitignore` files ;-) Each one says only about dirs where it is and downwards. And looking up stops as soon as `.git` dir is found. The same logic, but stopping condition is not external, but in the file itself.

But the length of the discussion says to me that probably, I propose something not so intuitive and simple as I thought it was. I started to hesitate that it's worth to be added.
