### ISSUE TITLE
[ feature request ] Add an ability to pass additional options to `rlwrap` when `pack repl`

### ISSUE THREAD

**Issue by buzden** [stefan-hoeck/idris2-pack#189]
Say, `-pGreen`, `--always-readline` etc.

**Comment by stefan-hoeck** [comment]
Sounds reasonable. This should both be a command line option and a setting in `pack.toml`. Do you think you could give this a go, since you are closer to the "argument escaping machinery" at the moment?

**Comment by buzden** [comment]
> Do you think you could give this a go, since you are closer to the "argument escaping machinery" at the moment?

I think, I can. Do you think, should be leave existing `idris2.repl.rlwrap` option as is and add something like `idris2.repl.rlwrap-options` for additional options?

**Comment by buzden** [comment]
I mean, alternatively, as far as I understand, we can accept both boolean, string and string list as an existing `idris2.repl.rlwrap` option with all blend of meanings whether run and not run `rlwrap` and run it with certain options. I'd do it this way, if it does not contradict your intentions to not to use different types to a single option.

**Comment by stefan-hoeck** [comment]
For me it's perfectly fine to (ab)use the flexibility we have in .toml files as long as the different possibilities are documented somewhere.
