### ISSUE TITLE
[ feature request ] Support a command for removing builds from unused collections

### ISSUE THREAD

**Issue by buzden** [stefan-hoeck/idris2-pack#190]
I've found that `~/.pack` is one of the biggest directories in my home O_O
But most of the time I move linearly from one collection to another, thus I don't need all previously built stuff.

**Comment by stefan-hoeck** [comment]
Yes. We need some form of garbage collection. I'll look into it.

**Comment by stefan-hoeck** [comment]
This has been implemented in #196. I leave this issue open for the time being in case the new command does not behave as expected. Feel free to close this, if the issue has been resolved.

**Comment by buzden** [comment]
I think it is. Couple more thoughts, I'm not sure worth a separate issue:
- I thought about an option to do automatic garbage collection after successful `switch`, but then I thought that maybe it is a needless complexity;
- Another thing is that garbage collection could also have clean up *local* builds for the current compiler version, maybe with some `--deep` flag. But, probably, this is again useless, since it has a timestamp control.
