### ISSUE TITLE
Support other code forges, or at least generic Git

### ISSUE THREAD

**Issue by toastal** [stefan-hoeck/idris2-pack#222]
Currently the code seems to suggest that `github` and `local` are the only allowed types. Generic Git can be decentralized and hosted by anyone, anywhere. It's probably not a good idea make users feel locked into a proprietary, closed-source forge owned by Microsoft.

**Comment by stefan-hoeck** [comment]
I assume, working with non-GitHub git repos already works (it does at least with local git repos), but the type is still called "github" for historic reasons. We could deprecate that name and replace it with just "git". For reasons of backward compatibility with older versions of pack, the name "github" will have to be kept in the "official" pack collections at least for a couple of months.

About other code forges: That would have to be implemented by someone else, or I'd need specific detailed guidance at the very least when adding support for them myself.

**Comment by buzden** [comment]
By the way, I always thought (having experience with some other tools) that when type of repo is `github`, not just a `git`, then I could use short name, like `stefan-hoeck/sop` instead of a full URL. So, in this case, renaming `github` identifier to `git` seems at least very logical.

**Comment by stefan-hoeck** [comment]
The favoring GitHub part has been fixed in #223 . Hence, I'll close this. Please open a new issue if you think we should support a specific additional code forge.

**Comment by toastal** [comment]
Wonderful work and quick turnaround. Thanks!
