### ISSUE TITLE
[ feature request ] Print license info in the `STATUS.md`

### ISSUE THREAD

**Issue by buzden** [stefan-hoeck/idris2-pack#228]
I think, at the moment, `STATUS.md` is used not only as a status of collection build, but as a reference of easy available packages. So, licensing info could be useful there. It can be taken from appropriate line of the `*.ipkg` file, along with brief info line.

**Comment by stefan-hoeck** [comment]
This should be trivial to add. I'll look into it later this week.

**Comment by buzden** [comment]
Only after you've implemented it I realised how many people are writing licenses in formats other than [SPDX](https://en.wikipedia.org/wiki/Software_Package_Data_Exchange) :-(

**Comment by stefan-hoeck** [comment]
> Only after you've implemented it I realised how many people are writing licenses in formats other than [SPDX](https://en.wikipedia.org/wiki/Software_Package_Data_Exchange) :-(

Well, the next step would now be to write PRs for those packages with non-standard license entries ;-). I'm afraid, I don't have the capacity to do that at the moment...
