### ISSUE TITLE
Provide `idris2` compatible wrapper command for IDE support

### ISSUE THREAD

**Issue by emdash** [stefan-hoeck/idris2-pack#239]
Provide a wrapper to the compiler in the package context.

The emacs idris-mode has an "idris-exectuable" variable, which it expects to point at the idris compiler.

This fails to find package-local dependencies. Pack's command-line syntax differs from that of the compiler itself, so some kind of compatibility wrapper which translates arguments as if it were the compiler seems like a reasonable stop-gap.

**Comment by buzden** [comment]
Once you've set up `pack` as written in the `INSTALL.md` (including setting your `PATH`) you have the `idris2` command, which is managed by `pack` and is, in fact, a script, computing appropriate version of a compiler and passing additional options, depending on the current configuration.

Have you put `~/.pack/bin` in your `PATH` before some other `idris2` paths, if some existed?

**Comment by emdash** [comment]
What I mean is that it's not clear how to run `idris2` in the context of
the project under development.

When I run `pack build`, obviously things are fine. But when emacs invokes
`idris2` for interactive editing, it can't see any of my project-local
dependencies, and interactive type-checking fails until I install those
same dependencies globally.

**Comment by stefan-hoeck** [comment]
> What I mean is that it's not clear how to run `idris2` in the context of the project under development. When I run `pack build`, obviously things are fine. But when emacs invokes `idris2` for interactive editing, it can't see any of my project-local dependencies, and interactive type-checking fails until I install those same dependencies globally.

Here is the wrapper script used for running Idris2. You can find this at `~/.pack/bin/idris2`:

```sh
#!/bin/sh

APPLICATION="$(/home/gundi/.pack/bin/pack app-path idris2)"
export IDRIS2_PACKAGE_PATH="$(/home/gundi/.pack/bin/pack package-path)"
export IDRIS2_LIBS="$(/home/gundi/.pack/bin/pack libs-path)"
export IDRIS2_DATA="$(/home/gundi/.pack/bin/pack data-path)"

$APPLICATION "$@"
```

As you can see, pack is being invoked to find the exact Idris executable to be used in the current context (`pack app-path idris2`), and it is the invoked again to setup the environment of currently installed packages.

And yes, you have to first install the dependencies of your local project (using `pack install-deps my_project.ipkg`) before they will be available to Idris. We've had this discussion before (on discord, if I remember correctly), whether the dependencies of a local project should be installed automatically when using idris2-lsp, and we decided against it, because in case of a failure it will be hard to figure out what went wrong. Even worse, if several `.ipkg` files are in scope, it will be impossible to tell which one is being used to install the dependencies.

You can of course provide this functionality yourself, if you'd like to have a different behavior: When starting your editor, look for a local `.ipkg` file and install the dependencies listed there (using `pack install-deps`) before you continue.

**Comment by l-monnier** [comment]
I had no issues with Idris 2 mode for vim, all packages from my `.ipkg` file are found.

However, I couldn't make it work with emacs, even after adding the `--find-ipkg` flag to the `Idris2 Interpreter Flags` using the `Customize` command. As mentioned above, this is indeed more an emacs issue than a pack one, but a bit of documentation somewhere would not hurt.

**Comment by stefan-hoeck** [comment]
> I had no issues with Idris 2 mode for vim, all packages from my `.ipkg` file are found.
> 
> However, I couldn't make it work with emacs, even after adding the `--find-ipkg` flag to the `Idris2 Interpreter Flags` using the `Customize` command. As mentioned above, this is indeed more an emacs issue than a pack one, but a bit of documentation somewhere would not hurt.

I'm not an emacs user, so I won't be able to provide documentation for this. However, if you think this would be useful to have documented in pack's README or installation instructions, I'll happily accept pull requests in this regard.

**Comment by l-monnier** [comment]
I tried to find other options, but failed... I've asked the question to the Idris 2 mode Emacs project. Let's see if I get an answer.

**Comment by emdash** [comment]
One question I have is: does pack keep per-project dependencies, like cargo
or npm? or does it install all packages into a global store?

**Comment by stefan-hoeck** [comment]
> One question I have is: does pack keep per-project dependencies, like cargo or npm? or does it install all packages into a global store?

Packages are installed in a global store. This is also documented in the [README](https://github.com/stefan-hoeck/idris2-pack#idris-compiler-and-libraries).

**Comment by emdash** [comment]
Okay, so that accounts for at least some of my confusion about how best to
do this.

**Comment by emdash** [comment]
As an aside, I tend to prefer at least the option to have project-local
dependencies, because the minute you start working on multiple projects you
can start getting into dependency conflicts between them. Granted, this is
more of a concern in business settings, but it comes up in open-source too.
Imagine I'm working on project Foo which depends on library Bar, but I'm
also contributing to Bar upstream. I might want to keep Foo on the latest
stable version, but I may also have dev branches of Foo that I test against
dev branches of Bar.

Anyway, forgive me if pack already supports this sort of thing. I read just
enough of the documentation to get started with it, and then dove straight
into working on my project. I do realize I need to take some time to
understand pack in more depth.

**Comment by stefan-hoeck** [comment]
Is this still an issue we need to keep open? The original question seems to have been answered, so I guess this can be closed? Feel free to reopen, if this needs to be discussed any further.

**Comment by l-monnier** [comment]
Yes, it can be closed. I've never managed to have Pack work properly with emacs but I'll have another attempt one day I've got sufficient time.
(On the other hand, it works very well for me with vim.)
