### ISSUE TITLE
[ ux ] Naming for executable-associated commands seems inconsistent

### ISSUE THREAD

**Issue by AlgebraicWolf** [stefan-hoeck/idris2-pack#240]
Currently, there are `install-app` , `remove-app` and `app-path` for performing system-wide operations with executable packages. However, to create a package that is meant to compile to an executable, one should use `pack new bin`  command.

In my opinion, the use of both `app` and `bin` is inconsistent and leads to confusion. Personally, I often try to use `pack new app` instead of proper command. I've asked @buzden, and he seems to experience the same issue. My suggestion is to replace `pack new bin` with `pack new app`, whilst leaving old syntax for backwards compatibility.

**Comment by stefan-hoeck** [comment]
You are right of course (and I have been bitten by this myself already). This is being fixed in #241
