### ISSUE TITLE
[ cache ] Pack caches removed modules

### ISSUE THREAD

**Issue by buzden** [stefan-hoeck/idris2-pack#242]
Consider I have a package `p1` with modules `X` and `Y` and consider I have a package `p2` depending on `p1` with module `Z` having `import X` and `import Y` in it.

Consider now that module `Y` of `p1` has been removed, but import in the package `p2` was not.

It turns out that after `pack install-deps p2 && pack run p2`, everything compiles and runs, if the previous version of `p1` had been installed on this machine, and expectedly does not compile on a machine that hadn't previous version of `p1` before.

**Comment by stefan-hoeck** [comment]
I assume you are talking about local packages here, not ones linked to a commit hash?

**Comment by stefan-hoeck** [comment]
I could reproduce this on my end and #243 seems to fix it. Please reopen this, if you still experience this issue.

**Comment by buzden** [comment]
Great, thank you!
