### ISSUE TITLE
[feature] Allow passing extra options to `idris2` executable from `pack` command line

### ISSUE THREAD

**Issue by 0xd34df00d** [stefan-hoeck/idris2-pack#269]
It'd be great if `pack` supported passing extra command line arguments to `idris2` from command line, so that it could be used like, say,
```shell
pack --rlwrap --extra-opts "--timing 10" repl SomeModule.idr
```
I'm deliberately focusing on command-line options as opposed to any extra fields in `pack.toml`, since the use case I have in mind is some one-off options that just don't deserve editing any extra files.

**Comment by stefan-hoeck** [comment]
Yes, we definitely need this! PRs are welcome, as I'm currently very busy with teaching. But maybe I'll find some time over the weekend.
