### ISSUE TITLE
Feature request: custom installation directories

### ISSUE THREAD

**Issue by foxyseta** [stefan-hoeck/idris2-pack#284]
Not sure if the titular feature would coincide or not with what is mentioned here:

https://github.com/stefan-hoeck/idris2-pack/blob/2ff76f3bf03337b269f4171829f7a33ad9c87336/README.md?plain=1#L298

**Comment by stefan-hoeck** [comment]
The item in the TODO list refers to build directories (as specified in .ipkg files). Currently, pack supports custom install directories via the `PACK_DIR` envirionment variable.

**Comment by foxyseta** [comment]
Whoops, true the README made that abundantly clear already. My bad Will try using that then. Thanks!
