### ISSUE TITLE
FC38, FC39 with racket 7.9  — ./bootstrap-stage1-racket.sh freezes on compilation

### ISSUE THREAD

**Issue by belonesox** [stefan-hoeck/idris2-pack#286]
Trying install idris2 with racket on Fedora with racket 7.9 (tested on FC38 and FC39, on several desktops, `racket-7.9-1.fc38.x86_64`, `racket-7.9-1.fc39.x86_64`)

Compilation `raco exe idris2_app/idris2-boot.rkt`  from `./bootstrap-stage1-racket.sh` hangs with 100% CPU utilization (waiting lot of hours, nothing interesed in verbose `--vv` in stdout, nothing interested in strace output…).

![image](https://github.com/stefan-hoeck/idris2-pack/assets/1609739/5d6be006-1fce-4277-92a5-29081da37c57)

![image](https://github.com/stefan-hoeck/idris2-pack/assets/1609739/1e4e799f-00a4-4dc2-8908-2a53b5419677)

With `Chez Scheme` (from `dnf copr enable superboum/chez-scheme`) compilation/installation goes OK.

**Comment by buzden** [comment]
Is this a problem of `pack`? Could you try to install `idris2` standalone and check if this problem is still present there?

**Comment by belonesox** [comment]
I am new in Idris, just follow installing instruction from this repo https://github.com/stefan-hoeck/idris2-pack/blob/main/INSTALL.md , and found the problem that can hurt someone else, so I reported it here. Probably this is bug in compiling some racket version, and this should noted in this INSTALL.md.

> Could you try to install idris2 standalone and check if this problem is still present there?

Sorry, cannot get what should I check. 
The bug is in bootstrapping, in compiling `raco exe idris2_app/idris2-boot.rkt` 
I cannot get how to installing idris2 (I can install it if I replace "racket" to "chez scheme") helps exploring the bug.

Maybe I should check different versions of Racket while compiling "idris2\_app/idris2-boot.rkt" or maybe I should fire some debug mode?

**Comment by belonesox** [comment]
Thank you, I fire [the bug](https://github.com/idris-lang/Idris2/issues/3261) in idris2 project, here bug can be closed.
