### ISSUE TITLE
[feature request] make <pkg or .ipkg> optional

### ISSUE THREAD

**Issue by isberg** [stefan-hoeck/idris2-pack#297]
It would be handy if `pack` when not given an explicit package would look for a package in the current folder and use that. It would simplify scripts when doing continuous integration.

**Comment by buzden** [comment]
I'd love this too. But what do you think `pack` should do in the case of several `ipkg` files? Just throw an error of ambiguity?

**Comment by isberg** [comment]
Considering that you might have just forgot to specify the package, I guess it would make sense to show the help, similar to how it works now, but perhaps says it found multiple package and that it refuse to choose. But personally I would be happy enough if it just choose one, if the other option was to much work to implement.
