### ISSUE TITLE
Advise users to use --bootstrap when too many versions have been skipped

### ISSUE THREAD

**Issue by andrevidela** [stefan-hoeck/idris2-pack#303]
There are cases where updating will fail because versions differ too much between the installed version and the latest version. In those cases the compiler needs to be bootstraped, but there is no way to know unless you've done this before. 

When the compiler fails to build, we should suggest to the user to run the same command with `--bootstrap`

**Comment by stefan-hoeck** [comment]
I have a PR ready that - instead of informing users - directly tries bootstrapping in cases where building Idris fails.

**Comment by andrevidela** [comment]
Nice, excellent idea
