### ISSUE TITLE
pack switch nightly-240524 : error compilong Pretty.idr  

### ISSUE THREAD

**Issue by maheshkronecker** [stefan-hoeck/idris2-pack#305]
Hello! After a fresh install of pack (nightly-240909), I tried 

`pack switch nightly-240519`

and got the error :

```
[ build ] 126/281: Building Idris.Pretty (src/Idris/Pretty.idr)
[ build ] Error: Couldn't parse any alternatives:
[ build ] 1: Unexpected end of expression.
[ build ] 
[ build ] Idris.Pretty:311:5--311:17
[ build ]  307 |     prettyPrec d (PDelayed _ _ ty) = parenthesise (d > startPrec) $ "Lazy" <++> prettyPrec appPrec ty
[ build ]  308 |     prettyPrec d (PDelay _ tm) = parenthesise (d > startPrec) $ "Delay" <++> prettyPrec appPrec tm
[ build ]  309 |     prettyPrec d (PForce _ tm) = parenthesise (d > startPrec) $ "Force" <++> prettyPrec appPrec tm
[ build ]  310 |     prettyPrec d (PAutoApp _ f a) =
[ build ]  311 |     parenthesise (d > startPrec) $ group $ prettyPrec leftAppPrec f <++> "@" <+> braces (pretty a)
[ build ]            ^^^^^^^^^^^^
[ build ] ... (2 others)
make: *** [Makefile:73: /home/zlizmk/.pack/.tmp0/idris2-compiler/build/exec/idris2] Error 1
[ fatal ] Error when executing system command.
          Command: "make" "idris2-exec" "PREFIX=/home/zlizmk/.pack/install/cf68e995c414912c338ae694a74fd833a6c4cee2/idris2" "SCHEME=chezscheme"
          Error code: 2
```
As a side remark : I have looked for a way to directly install nightly-240519, but  could not find how to do this. Version nightly-240519 is the version deployed at my college and I need the same version on my computer.

Thank you.

**Comment by buzden** [comment]
Try `pack --bootstrap switch nightly-240519`. This will use the release version of the compiler rather than the current one, but will increase the time of switching.

**Comment by maheshkronecker** [comment]
Indeed, it worked, many thanks, and sorry if that was documented somewhere and I'd missed it.

**Comment by stefan-hoeck** [comment]
Pack should actually do this automatically: If building Idris without bootstrapping fails, bootstrapping should be tried instead. I opened a PR for this: #306.
