### ISSUE TITLE
Transitive dependencies

### ISSUE THREAD

**Issue by Z-snails** [stefan-hoeck/idris2-pack#32]
I don't know if this should be here or in the idris2 repo

Currently you have to list every dependency that is transitively used by that packages you actually need, this is very annoying and tedious.

Now I think about it, this is probably an idris2 issue not pack

**Comment by stefan-hoeck** [comment]
Theoretically, if all transitive dependencies are known to *pack* (as they should be anyway), we could use this info to append them to the Idris executable we use in *pack*'s system calls: `idris2 -p d1 - p d2 ...`. However, this seems a bit hacky, so it might be best to solve this for Idris in general. However, *pack* is already set up to install dependencies transitively prior to building a package.

**Comment by Z-snails** [comment]
This has been fixed upstream (https://github.com/idris-lang/Idris2/pull/2469)
