### ISSUE TITLE
Add support for different backends

### ISSUE THREAD

**Issue by andrevidela** [stefan-hoeck/idris2-pack#45]
Codegens for different backends would be nice, currently it does not compile dependencies according to the backend selected for the target binary.

**Comment by stefan-hoeck** [comment]
This has been open for a long time, and I'm not sure if this is still an issue or the `--gc` command-line option is enough. I'm going to close this, because I'd like to clean up the issue tracker a bit. Feel free to reopen, if this requires further work.
