### ISSUE TITLE
Disable incremental compilation when compiling idris2

### ISSUE THREAD

**Issue by Z-snails** [stefan-hoeck/idris2-pack#57]
This probably doesn't provide any significant speed up to compilation*, and causes a noticable slowdown when starting idris, as the following benchmark shows

*compilation of the idris compiler

```nu
/home/zoe〉benchmark {  ~/.idris2/bin/idris2 --no-prelude --client ":q" }
399ms 735us 107ns
/home/zoe〉benchmark {  idris2 --no-prelude --client ":q" }
1sec 363ms 491us 225ns
```
(This is nushell btw, `benchmark` = `time`)

**Comment by Z-snails** [comment]
This can be done by adding `IDRIS2_INC_CGS=` to the env before calling `make all` or by patching the make file to add `--whole-program` to any calls that build the idris2 compiler.

**Comment by Z-snails** [comment]
This might also want to apply to apps installed with `pack install`, or maybe we want that to be a command line option/pack.toml config

**Comment by stefan-hoeck** [comment]
Having never worked with incremental compilation, I need some context here. Will your suggestions disable incremental compilation for the Idris compiler used by pack in general, or just when invoking it with this environmental variable set? If yes, is this desirable in general (this compiler will probably also be used for developing libraries and applications)?

**Comment by Z-snails** [comment]
Incremental compilation should be enabled while compiling libraries. This is because idris needs to create `.so` files for each module.

While building a binary, if incremental compilation is enabled, and every module that is used by the final binary has an associated `.so` file, the final compilation step basically just links together all the `.so` files, so it is much faster to compile. Because it's all dynamically loaded libraries it takes a while to load them all at startup (at least for chez scheme)

No matter how the idris2 compiler is built, incremental compilation can be used.

Incremental compilation can be enabled with the `IDRIS2_INC_CGS=chez` environment variables, or with a command line option.

Whole program compilation can be enabled for a specific binary build with the `--whole-program` flag.

Incremental compilation is really helpful when hacking on the idris2 compiler, it takes compile times down from a few minutes to a few seconds, so I definitely think pack should support it. Perhaps with a command line flag.

**Comment by Z-snails** [comment]
So let's start with building idris2:
1 - `make all` should be split into `make support`, `make idris2-exec` then `make libs`
2 - `make idris2-exec` should be run with env var `IDRIS2_INC_CGS=` (this saves time as idris doesn't have to compile chez for each module then compile the entire thing again for whole program compilation)
3 - all other `make` commands should not change env vars.


For installing apps:
This is my opinion only, other people may disagree
Add a `--whole-program` and `--incremental` switch. The default value for this pair of switches can be controlled by `pack.toml` but in case it's missing, I think `--whole-program` for apps in the pack-db and `--incremental` for local `.ipkg`s

When `--whole-program` is enabled, this option is passed to the idris2 compiler; `--incremental` simply disables `--whole-program` that way the `IDRIS2_INC_CGS` env var is never messed with.


If this doesn't make sense, let me know and I can implement it hopefully over the weekend.

**Comment by Z-snails** [comment]
Ok, I've thought of a much easier way to compile idris with whole program compilation: use `patch` to set the `opts` field of `idris2.ipkg` to have `--whole-program`
I don't know how patch works so I'll leave that to you @stefan-hoeck if you are happy doing that otherwise I can try and figure it out.

**Comment by stefan-hoeck** [comment]
Patching `.ipkg` files does not yet work for Idris itself. Also, I think a command-line flag would make more sense here. I'll see if I can come up with a PR over the next couple of days, then I'll flag you to review it, if that's OK for you.

**Comment by Z-snails** [comment]
Do you mean a command line flag to disable incremental compilation during compilation of idris2?
Because pack installs it to a fresh directory, incremental compilation doesn't bring a significant speedup to the compilation time of idris2, but it does have a substantial cost, so in my opinion, it makes more sense to always disable incremental compilation during compilation of the idris2 compiler.

(sorry if I've misunderstood what you've suggested, possibly we are talking about different things, ie are you talking about compiling other packages?)

**Comment by stefan-hoeck** [comment]
Is this still actual, that is, are there still issues with regard to incremental compilation, pack should take care of?

**Comment by stefan-hoeck** [comment]
I'm closing this for now. Feel free to reopen if this requires additional work.
