### ISSUE TITLE
Allow using local git repository of idris2 compiler

### ISSUE THREAD

**Issue by locriacyber** [stefan-hoeck/idris2-pack#61]
Ideas about how to make pack reuse Idris source code.

1. Prompt the user for a git remote URL when trying to download the Idris repo. This URL may be a local directory, allowing cloning locally.
2. When doing `pack install idris2.ipkg` inside Idris repo, don't try to download the Idris repo again.
3. Make idris standard library have individual version numbers. It doesn't make sense to have the same version number for compiler and standard library.

**Comment by stefan-hoeck** [comment]
> Ideas about how to make pack reuse Idris source code.
> 
>     1. Prompt the user for a git remote URL when trying to download the Idris repo. This URL may be a local directory, allowing cloning locally.

If you want to change the URL where to look for the Idirs compiler, you can change it in the `.toml` file of the package collection you use. For instance, if you use `nightly-220529`, the corresponding `.toml` file can be found at `~/.pack/db/nightly-220529.toml`. There, you can change to URL of the Idris repo to use. I haven't tested this with local URLs, though. Feel free to give it a go and report back here if it doesn't work.

>     2. When doing `pack install idris2.ipkg` inside Idris repo, don't try to download the Idris repo again.

If you already have a version of the Idris compiler managed by pack, this will not reinstall Idris and therefore not download the Idris repo. If you don't yet have an Idris compiler managed by pack, pack does not have the means to build and install `idris2.ipkg`. It will therefore clone the Idris repo the current data collection points to, and install the Idris compiler it finds there.

>     3. Make idris standard library have individual version numbers. It doesn't make sense to have the same version number for compiler and standard library.

I think this is an upstream issue and not something pack can fix.

**Comment by locriacyber** [comment]
Changing the URL in `~/.pack/db/nightly-220529.toml` worked. Is it possible to make a settings where I can overwrite package URL? This is useful for other packages as well (for local development).

**Comment by locriacyber** [comment]
I have the following section in `~/.pack/user/pack.toml`. Pasted here as documentation.
Downside is, I need to use git myself to update Idris2.

```
[idris2]

# Whether to build Idris2 with its bootstrap compiler.
# Bootstrapping takes longer than building with an existing
# Idris2 installation, but it will work even if the existing
# Idris2 compiler is outdated.
bootstrap  = false

# Name or path to the scheme executable to use.
scheme      = "scheme"

# Set this to `true` in order to run REPL sessions from within
# `rlwrap`. This will give you additional features such as a
# command history.
repl.rlwrap = true

url = "path/to/Idris2/"
path = "path/to/Idris2/"
```

**Comment by locriacyber** [comment]
I got confused. It's not working.

**Comment by stefan-hoeck** [comment]
With the latest commit, it is possible to add fields `idris2.url`, `idris2.commit`, `pack.url`, and `pack.commit` to the `pack.toml` file. Could you please check whether this works as expected?

**Comment by locriacyber** [comment]
It has another error.
```
> pack exec pack.ipkg
Uncaught error: Error: Error: Source file "pack.ipkg" is not in the source directory "/home/user/computing/tool/idris2-pack/src"
Error when executing system command.
Command: /home/user/.pack/install/2aaad190fb62ca953acf13b0e333e2d2002a2d76/idris2/bin/idris2 --source-dir "src" -p base -p contrib -p idris2 -p toml -p filepath -o _tmppack pack.ipkg
Error code: 1
```

**Comment by locriacyber** [comment]
It's working as expected. I only tried `idris2.url`

**Comment by stefan-hoeck** [comment]
> It has another error.
> 
> ```
> > pack exec pack.ipkg
> Uncaught error: Error: Error: Source file "pack.ipkg" is not in the source directory "/home/user/computing/tool/idris2-pack/src"
> Error when executing system command.
> Command: /home/user/.pack/install/2aaad190fb62ca953acf13b0e333e2d2002a2d76/idris2/bin/idris2 --source-dir "src" -p base -p contrib -p idris2 -p toml -p filepath -o _tmppack pack.ipkg
> Error code: 1
> ```
`pack exec` only works with Idris source file. To execute an application specified by a package from the collection or by an `.ipkg` file, use `pack run`. See also the two commands in the help text.

**Comment by stefan-hoeck** [comment]
> It's working as expected. I only tried `idris2.url`

Thanks for checking. I close this then.
