### ISSUE TITLE
Change convention around `.ipkg` file naming

### ISSUE THREAD

**Issue by alexhumphreys** [stefan-hoeck/idris2-pack#85]
Right now the tendency is to name the ipkg file as `$package.ipkg`. Eg [pack](https://github.com/stefan-hoeck/idris2-pack/blob/main/pack.ipkg), [idrall](https://github.com/alexhumphreys/idrall/blob/main/idrall.ipkg), [idris2](https://github.com/idris-lang/Idris2/blob/main/idris2.ipkg).

This makes some sense for repos where there's multiple packages, but maybe as a convention we should have a standard name for this file. Random thoughts would be `main.ipkg`, `package.ipkg`, `idris.ipkg`. I'm not too picky on what name is, just that there's a convention so it's a bit easier to know what to type when I want to "edit the `.ipkg` file".

Having a standard name would also be similar to other languages, eg. `package.json` for node, `requirements.txt` for python, `cargo.toml` in rust. Some of these are serving slightly different purposes than the `.ipkg` file, but hopefully the idea across.

Should we land on a name then might make sense to change [this proposed `new` command](https://github.com/stefan-hoeck/idris2-pack/pull/58/files#diff-6bcdd6a6eab716f8f5c63aa15da682522d602fd878af05a40cb2d28d22a4fa68R85) and the idris2 equivalent `--init` to match.

I'm also not suggesting any fancy automation based on this "standard" name, but just to have a standard name guideline to begin with.

**Comment by locriacyber** [comment]
idris2-lsp currently index packages in ~/.idris2/xxxx (I think it's hard coded)

As for `--find-ipkg`: https://github.com/idris-lang/Idris2/issues/2524. Need to modify Idris2 to do that

**Comment by stefan-hoeck** [comment]
> idris2-lsp currently index packages in ~/.idris2/xxxx (I think it's hard coded). It uses similar/same logic as --find-ipkg to get dependencies. Packages have to be installed with `install-src` for go-to-declaration to work for dependencies.

I'm not sure I follow. idris2-lsp uses the same mechanism to look for packages as does Idris itself. If you set the `IDRIS2_PACKAGE_PATH` correctly, lsp will find the packages installed by pack (Disclaimer: I'm using lsp plus pack daily and it works very well).

**Comment by locriacyber** [comment]
Sorry, I was using an old version of lsp and pack. Now that I upgraded both, it works.

Slight problem: `pack install-app lsp` doesn't create  `~/.pack/bin/idris2-lsp`. I did it manually with `ln -s`.

**Comment by stefan-hoeck** [comment]
> Sorry, I was using an old version of lsp and pack. Now that I upgraded both, it works.
> 
> Slight problem: `pack install-app lsp` doesn't create `~/.pack/bin/idris2-lsp`. I did it manually with `ln -s`.

This will not work correctly: `idris2-lsp` in `~/.pack/bin` should be a wrapper script with the package paths set correctly. It could be that you still had a built version of the `lsp` app in your pack dirs but the wrapper script was missing, so pack though it was already installed. Could you please try the following: Remove the `lsp` app: `pack remove-app lsp` and now re-install it and check, whether the wrapper script has now been generated.

**Comment by locriacyber** [comment]
`remove-app` is unknown command... I don't know how to check pack's app version

**Comment by emdash** [comment]
Does it make sense to have a section in `pack.toml` which enumerates the `.ipkg` files which belong to the project?

**Comment by stefan-hoeck** [comment]
> Does it make sense to have a section in `pack.toml` which enumerates the `.ipkg` files which belong to the project?

I don't think so. Currently, from pack's point of view, a package must have exactly one `.ipkg` file and this is already specified in the `pack.toml` files. If you have several `.ipkg` files, then that's several packages, each of which can be specified in your `pack.toml` files.

Or maybe I misunderstood your question and you are asking whether it is necessary to specify the `.ipkg` file at all? In that case the answer is "yes", because in certain situations it makes sense to have several `.ipkg` files in a directory because they describe different packages/executables which mostly share the same code base. The pack project itself is an example for such a setup.

**Comment by stefan-hoeck** [comment]
I'm going to close this since it has not seen any activity for several months and it seems the way we currently handle and name `.ipkg` files seems to work fine for most people. Feel free to reopen, if this requires further action.
