### ISSUE TITLE
[ feature ] option to only build `depends`

### ISSUE THREAD

**Issue by alexhumphreys** [stefan-hoeck/idris2-pack#89]
I have a [dockerfile here](https://github.com/alexhumphreys/dummy-server/blob/main/Dockerfile#L11) where i'm building a project. Building the project itself is quite fast, but building the dependencies takes quite some time. It would be nice to be able to split the `build` step into two phases like `build-depends` and `build`. That way I could cache the results of `build-depends` then have a faster turn around time.

You can see an example of the same trick [here](https://algorithmicallysound.com/2016/11/12/dockerize-a-ruby-application/) for ruby. First they copy in the `Gemfile` so they can `bundle install` the dependencies as that takes some time. Then they copy the application which changes much more frequently.

Maybe this is a bit docker specific, but maybe it's a useful feature in other situations.

**Comment by stefan-hoeck** [comment]
You can still decide on the name of the command: #90

**Comment by alexhumphreys** [comment]
Oh damn that was fast, thank you! ❤️

**Comment by alexhumphreys** [comment]
[This rules](https://github.com/alexhumphreys/dummy-server/blob/main/Dockerfile#L17)! Taking like 15 minutes off my builds :D
