### ISSUE TITLE
[FeatureRequest] Allow depending on the latest version of a package

### ISSUE THREAD

**Issue by ohad** [stefan-hoeck/idris2-pack#96]
A project sometimes co-develops multiple packages, on different repos. When that happens, we usually keep each repo up to date with the other repos. It would be nice to be able to specify dependency on the latest version of a package. Since we want the DB's package sets to be mutually-consistent, maybe we only need this capability in a local package set, or a local configuration.

**Comment by stefan-hoeck** [comment]
Here's an idea: We could support some special syntax to specify the latest commit of a branch in the `pack.toml` files. For instance:

```toml
[custom.all.foo]
type      = "github"
url         = "https://github.com/bar/foo"
commit = "latest:devel"
ipkg      = "foo.ipkg"
```

Whenever pack resolves this package, it would first fetch the latest commit hash from the `devel` branch on GitHub. If the package has been updated and is needed (for instance, as a dependency) in the current pack run, pack would automatically install the updated version. What do you think?

**Comment by ohad** [comment]
This now works really well, but I agree about the slow-down.
A side-effect of the slow-down is that downstream projects like [`idris2-mode`](http://www.github.com/idris-community/idris2-mode) assume a faster start-up time and time-out too early giving error messages like:
```
idris2-send: Buffer Demo.idr has no process
```
(For `idris2-mode`, it's enough to just wait for the few seconds it takes to check we have the latest and it does start-up fine. But this behaviour is confusing to users, and also other projects might not recover as easily.)

So maybe we can have something else, for example:
* `latest:master` means we use the local copy, 
* `fetch-latest:master` means we always try to fetch the latest copy (current behaviour).
We can have a command for fetching all the latest packages in the current set: `pack upgrade` or `pack fetch` (I don't have a preference for the name).

**Comment by stefan-hoeck** [comment]
What do you think about having a new type of package:

```toml
[custom.all.foo]
type = "local-git"
path = "../path/to/foo"
ipkg = "relative/path/to/foo.ipkg"
```

And a command `pack fetch`, which would enter the directories of all local git projects and run `git pull` there? Pack already uses a timestamp for local packages to make sure that in case of changes to the package it gets reinstalled automatically before being used as a dependency. We could use this here as well.

If you want to support using custom branches, we could add an additional `branch` field to the spec.

**Comment by stefan-hoeck** [comment]
@ohad Would you prefer it if pack actually used a local clone of a GitHub repo, or if it just stored the current package commits to use somewhere in the `$HOME/.pack` directory (updating them when `pack fetch` is run`)? The latter is easier to implement and it does not infer with the local GitHub clones you might have.

**Comment by stefan-hoeck** [comment]
This has been implemented and improved, so I'm closing the issue. Feel free to reopen this (or open a new issue) if this requires additional work.
